// components/evaluations/evalStrings.js
//
// Page-chrome + modal translations (Arabic + English) shared by the supervisor
// and DIO evaluation flows. Dynamic data (names, dates, hospitals) and the
// evalForms-driven form content are NOT translated here. Pages may overlay a
// few keys (e.g. search placeholder / empty-state hints) on top of these.
export const EVAL_STRINGS = {
  ar: {
    key: 'العربية',
    statTotal: 'إجمالي التقييمات',
    statThisMonth: 'هذا الشهر',
    statFinalized: 'تم الاعتماد',
    searchPlaceholder: 'ابحث باسم المتدرب أو الرقم…',
    emptyNoTrainees: 'لا يوجد متدربون معينون بعد',
    emptyNoMatch: 'لا يوجد متدربون يطابقون بحثك',
    emptyHint: 'يتم تعيين المتدربين لك من قبل السكرتارية.',
    evaluationsTotal: 'تقييم إجمالي',
    formsThisMonth: 'نماذج هذا الشهر',
    allFormsDone: 'اكتملت كل النماذج',
    view: 'عرض',
    evaluation: 'تقييم',
    evaluationsBtn: 'التقييمات',
    // modal
    idLabel: 'الرقم',
    monthlyEvaluations: 'التقييمات الشهرية',
    monthProgress: 'تقدم الشهر',
    forms: 'نماذج',
    competencyDomains: 'مجالات الكفاءة',
    doneThisMonth: 'تم هذا الشهر',
    notSubmitted: 'لم يُقدَّم',
    start: 'بدء',
    noFormsAvailable: 'لا توجد نماذج تقييم متاحة حاليًا لهذا الشخص.',
    submittedEvaluations: 'التقييمات المُقدَّمة',
    sentToGrades: 'أُرسل إلى الدرجات',
    finalize: 'اعتماد',
    sending: 'جارٍ الإرسال…',
    noEvalsYet: 'لا توجد تقييمات بعد لهذا المتدرب',
    print: 'طباعة',
    printTitle: 'طباعة نموذج التقييم',
    // structured form
    trainee: 'المتدرب',
    assessor: 'المُقيِّم',
    date: 'التاريخ',
    caseDetails: 'تفاصيل الحالة',
    competencyRatings: 'تقييم الكفاءات',
    scale: 'المقياس',
    feedback: 'الملاحظات',
    select: 'اختر…',
    back: 'رجوع',
    completeToPrint: 'أكمل كل التقييمات للطباعة',
    printThisForm: 'طباعة نموذج التقييم هذا',
    submitting: 'جارٍ الإرسال…',
    submit: 'إرسال',
    rateAllDomains: 'يرجى تقييم جميع مجالات الكفاءة.',
    pleaseSelect: 'يرجى اختيار',
    // toasts
    loadFailed: 'فشل تحميل البيانات',
    submitSuccess: 'تم إرسال التقييم بنجاح',
    sentToGradesToast: 'أُرسل التقييم إلى صفحة درجات المتدرب',
    submitFailed: 'فشل إرسال التقييم.',
    finalizeFailed: 'فشل اعتماد التقييم.',
  },
  en: {
    key: 'English',
    statTotal: 'Total Evaluations',
    statThisMonth: 'This Month',
    statFinalized: 'Finalized',
    searchPlaceholder: 'Search by trainee name or ID…',
    emptyNoTrainees: 'No trainees assigned yet',
    emptyNoMatch: 'No trainees match your search',
    emptyHint: 'Trainees are assigned to you by the secretary.',
    evaluationsTotal: 'total',
    formsThisMonth: 'forms this month',
    allFormsDone: 'All forms done',
    view: 'View',
    evaluation: 'Evaluation',
    evaluationsBtn: 'Evaluations',
    // modal
    idLabel: 'ID',
    monthlyEvaluations: 'Monthly evaluations',
    monthProgress: 'progress',
    forms: 'forms',
    competencyDomains: 'competency domains',
    doneThisMonth: 'Done this month',
    notSubmitted: 'Not submitted',
    start: 'Start',
    noFormsAvailable: 'No evaluation forms are currently available for this person.',
    submittedEvaluations: 'Submitted Evaluations',
    sentToGrades: 'Sent to grades',
    finalize: 'Finalize',
    sending: 'Sending…',
    noEvalsYet: 'No evaluations yet for this trainee',
    print: 'Print',
    printTitle: 'Print evaluation form',
    // structured form
    trainee: 'Trainee',
    assessor: 'Assessor',
    date: 'Date',
    caseDetails: 'Case Details',
    competencyRatings: 'Competency Ratings',
    scale: 'Scale',
    feedback: 'Feedback',
    select: 'Select…',
    back: 'Back',
    completeToPrint: 'Complete all ratings to print',
    printThisForm: 'Print this evaluation form',
    submitting: 'Submitting…',
    submit: 'Submit',
    rateAllDomains: 'Please rate all competency domains.',
    pleaseSelect: 'Please select the',
    // toasts
    loadFailed: 'Failed to load data',
    submitSuccess: 'Evaluation submitted successfully',
    sentToGradesToast: "Evaluation sent to trainee's grades page",
    submitFailed: 'Failed to submit evaluation.',
    finalizeFailed: 'Failed to finalize evaluation.',
  },
};
